### ISSUE TITLE
[C++] Support path dependent options

### ISSUE THREAD

**Issue by KYLChiu** [KYLChiu/ExoticMonteCarloEngine#36]

**Comment by KYLChiu** [comment]
Down and out and Geometric discrete Asian done.

**Comment by KYLChiu** [comment]
https://en.wikipedia.org/wiki/Lookback_option

Others to consider:
puts, other barriers, arithmetic Asian options

**Comment by ccjeremylo** [comment]
@KYLChiu Think this issue can be closed by #33 ?

**Comment by KYLChiu** [comment]
Will close this one and add another one for lookbacks/arithmetic Asian options/more barriers - anything else you think we should add?
