### ISSUE TITLE
[C++] Add support for first-order greeks

### ISSUE THREAD

**Issue by KYLChiu** [KYLChiu/ExoticMonteCarloEngine#38]

**Comment by KYLChiu** [comment]
In the future - autodiff but for now use finite diff

**Comment by ccjeremylo** [comment]
@KYLChiu What is auto diff? Do you mean AD/AAD (adjoint algorithmic differentiation)?

**Comment by KYLChiu** [comment]
I thought algorithmic differentiation and automatic differentiation are the same thing :)
